name: Swagswagy23

on:
  workflow_dispatch:
  schedule:
    - cron: "* * * * *"

jobs:
  npm-automation:
    runs-on: ubuntu-latest
    steps:
      - name: Check it out
        uses: actions/checkout@v3
      - name: Set it up
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*" 
      - name: Install it
        run: npm install -g dependency-insight
      - name: Confirm it
        run: npm uninstall -g dependency-insight
      - name: Goodbye
        run: npm cache clean --force
        
